self.addEventListener("install",e=>{
e.waitUntil(
caches.open("faaliyet").then(c=>
c.addAll([
"index.html","kayit.html","detay.html",
"style.css","app.js","acilis.mp4"
])
)
);
});
self.addEventListener("fetch",e=>{
e.respondWith(caches.match(e.request).then(r=>r||fetch(e.request)));
});